version: '3.8'

services:
  django_app:
    build: .
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
  
  nginx:
    image: nginx:1.19-alpine
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - 8083:80
    depends_on:
      - django_app
  
volumes:
  static_volume:
  media_volume:
