name: CI CD Django

on:
    push:
        branches:
            - main

jobs:
    build:

        runs-on: self-hosted
        strategy:
            max-parallel: 4
            matrix:
                python-version: [3.10.12]

        steps:
            - name: Give permission to execute
              run: |
                sudo chown -R user_test:user_test /home/user_test
                sudo chmod -R u+rwx /home/user_test
            - name: Checkout
              uses: actions/checkout@v2
            
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v2
              with:
                  python-version: ${{ matrix.python-version }}
            
            - name: Set docker compose config
              run: |
                docker-compose up -d --build
